import Base
import ./LAWS.bend as Laws

def Laws.identity(x):
  {==}

def Laws.square(x):
  {==}

def Laws.increment(x):
  {==}

def Laws.add(x, y):
  {==}

def Laws.flip_involution(x):
  match x:
    case False{}:
      {==}
    case True{}:
      {==}

def Laws.countdown_zero(acc):
  {==}

def Laws.countdown_step(n, acc):
  {==}

def Laws.rounds_zero(acc):
  {==}

def Laws.rounds_step(n, acc):
  {==}
